version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      #- APP_ENV=${APP_ENV:-production}
      #- N8N_BASIC_AUTH_ACTIVE=true
      #- N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      #- N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      #- N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_HOST=n8n.globalhenning.se
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      #- WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - WEBHOOK_URL=https://n8n.globalhenning.se/
      #- GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - GENERIC_TIMEZONE=Europe/Stockholm
      #- TZ=${GENERIC_TIMEZONE}
      - TZ=Europe/Stockholm
      #- DB_TYPE=mariadb
      #- DB_MYSQLDB_HOST=10.10.10.58
      #- DB_MYSQLDB_DATABASE=n8n
      #- DB_MYSQLDB_PORT=3306
      #- DB_MYSQLDB_USER=n8n
      #- DB_MYSQLDB_PASSWORD=gOmSpOA7Ug0
      #- DB_TYPE=postgresdb    
      #- DB_POSTGRESDB_DATABASE=n8n
      #- DB_POSTGRESDB_HOST=10.10.10.69
      #- DB_POSTGRESDB_PORT=5432
      #- DB_POSTGRESDB_USER=n8n
      #- DB_POSTGRESDB_SCHEMA=
      #- DB_POSTGRESDB_PASSWORD=RsVhJkeY&DM3BCpk
    volumes:
      #- ./html:/usr/share/nginx/html:ro
      - data:/home/node/.n8n
    restart: unless-stopped

volumes:
  data:
    driver: local

# Add more services as needed
# networks:
#   default:
#     driver: bridge


# .env
# SUBDOMAIN=n8n
# DOMAIN_NAME=globalhenning.se
# GENERIC_TIMEZONE=Europe/Stockholm
