services:
    semaphore:
        ports:
            - 3001:3000
        image: semaphoreui/semaphore:v2.16.51
        environment:
            SEMAPHORE_DB_DIALECT: sqlite
            SEMAPHORE_ADMIN: henning
            SEMAPHORE_ADMIN_PASSWORD: astrix
            SEMAPHORE_ADMIN_NAME: Henning
            SEMAPHORE_ADMIN_EMAIL: henning@globalhenning.se
            SEMAPHORE_USE_REMOTE_RUNNER: "True"
            SEMAPHORE_RUNNER_REGISTRATION_TOKEN: "dpck/vr4DPqHTtcqynG49sSjbpEv7XIieTjjj3KtfyA="
        volumes:
            - semaphore_data:/var/lib/semaphore
            - semaphore_config:/etc/semaphore
            - semaphore_tmp:/tmp/semaphore
volumes:
    semaphore_data:
    semaphore_config:
    semaphore_tmp:
