services:
    semaphore:
        ports:
            - 3000:3000
        image: public.ecr.aws/semaphore/pro/server:v2.16.51
        environment:
            SEMAPHORE_DB_DIALECT: sqlite
            SEMAPHORE_ADMIN: henning
            SEMAPHORE_ADMIN_PASSWORD: astrix
            SEMAPHORE_ADMIN_NAME: Henning
            SEMAPHORE_ADMIN_EMAIL: henning@globalhenning.se
